version: '3.5'

services:
   postgres:
    image: postgres
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_HOST=postgres
   web:
    ports:
      - "3000:3000"
    build:
      context: .
      dockerfile: ./dockerfile
    environment:
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_USER=postgres
      - DB_PASSWORD=postgres
    tty: true
    volumes:
      - .:/recipes
      - gems_volume:/usr/local/bundle
    depends_on:
      - postgres
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"

volumes:
  postgres: {}
  gems_volume: {}
